name: Update Image List

on:
  push:
    paths:
      - 'sites/PictureFrame/img/**' # Trigger only when files in the img folder are changed

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install fs path

      - name: Run script
        run: node sites/PictureFrame/updateImageList.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sites/PictureFrame/imageList.json
          git commit -m "Update image list"
          git push
